# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(711, 455)
        self.progressBar_v1 = QtGui.QProgressBar(Form)
        self.progressBar_v1.setGeometry(QtCore.QRect(110, 50, 118, 23))
        self.progressBar_v1.setProperty("value", 0)
        self.progressBar_v1.setObjectName(_fromUtf8("progressBar_v1"))
        self.progressBar_v2 = QtGui.QProgressBar(Form)
        self.progressBar_v2.setGeometry(QtCore.QRect(240, 420, 118, 23))
        self.progressBar_v2.setProperty("value", 0)
        self.progressBar_v2.setObjectName(_fromUtf8("progressBar_v2"))
        self.progressBar_v3 = QtGui.QProgressBar(Form)
        self.progressBar_v3.setGeometry(QtCore.QRect(580, 420, 118, 23))
        self.progressBar_v3.setProperty("value", 0)
        self.progressBar_v3.setObjectName(_fromUtf8("progressBar_v3"))
        self.pushButton_v1_enviar = QtGui.QPushButton(Form)
        self.pushButton_v1_enviar.setGeometry(QtCore.QRect(170, 20, 51, 27))
        self.pushButton_v1_enviar.setObjectName(_fromUtf8("pushButton_v1_enviar"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 701, 461))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("tanque.jpg")))
        self.label.setObjectName(_fromUtf8("label"))
        self.spinBox_v1 = QtGui.QSpinBox(Form)
        self.spinBox_v1.setGeometry(QtCore.QRect(110, 20, 51, 27))
        self.spinBox_v1.setMaximum(100)
        self.spinBox_v1.setObjectName(_fromUtf8("spinBox_v1"))
        self.pushButton_v2_enviar = QtGui.QPushButton(Form)
        self.pushButton_v2_enviar.setGeometry(QtCore.QRect(300, 390, 51, 27))
        self.pushButton_v2_enviar.setObjectName(_fromUtf8("pushButton_v2_enviar"))
        self.spinBox_v2 = QtGui.QSpinBox(Form)
        self.spinBox_v2.setGeometry(QtCore.QRect(240, 390, 51, 27))
        self.spinBox_v2.setMaximum(100)
        self.spinBox_v2.setObjectName(_fromUtf8("spinBox_v2"))
        self.pushButton_v3_enviar = QtGui.QPushButton(Form)
        self.pushButton_v3_enviar.setGeometry(QtCore.QRect(640, 390, 51, 27))
        self.pushButton_v3_enviar.setObjectName(_fromUtf8("pushButton_v3_enviar"))
        self.spinBox_v3 = QtGui.QSpinBox(Form)
        self.spinBox_v3.setGeometry(QtCore.QRect(580, 390, 51, 27))
        self.spinBox_v3.setMaximum(100)
        self.spinBox_v3.setObjectName(_fromUtf8("spinBox_v3"))
        self.lineEdit_t1 = QtGui.QLineEdit(Form)
        self.lineEdit_t1.setGeometry(QtCore.QRect(60, 230, 81, 31))
        self.lineEdit_t1.setObjectName(_fromUtf8("lineEdit_t1"))
        self.lineEdit_t2 = QtGui.QLineEdit(Form)
        self.lineEdit_t2.setGeometry(QtCore.QRect(380, 220, 81, 31))
        self.lineEdit_t2.setObjectName(_fromUtf8("lineEdit_t2"))
        self.lineEdit_mix = QtGui.QLineEdit(Form)
        self.lineEdit_mix.setGeometry(QtCore.QRect(410, 330, 181, 27))
        self.lineEdit_mix.setInputMask(_fromUtf8(""))
        self.lineEdit_mix.setObjectName(_fromUtf8("lineEdit_mix"))
        self.progressBar_t1 = QtGui.QProgressBar(Form)
        self.progressBar_t1.setGeometry(QtCore.QRect(190, 140, 21, 131))
        self.progressBar_t1.setMaximum(1000)
        self.progressBar_t1.setProperty("value", 0)
        self.progressBar_t1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_t1.setObjectName(_fromUtf8("progressBar_t1"))
        self.progressBar_t2 = QtGui.QProgressBar(Form)
        self.progressBar_t2.setGeometry(QtCore.QRect(520, 200, 21, 121))
        self.progressBar_t2.setMaximum(200)
        self.progressBar_t2.setProperty("value", 0)
        self.progressBar_t2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_t2.setObjectName(_fromUtf8("progressBar_t2"))
        self.groupBox_mix = QtGui.QGroupBox(Form)
        self.groupBox_mix.setGeometry(QtCore.QRect(570, 200, 120, 80))
        self.groupBox_mix.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_mix.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_mix.setFlat(False)
        self.groupBox_mix.setCheckable(False)
        self.groupBox_mix.setObjectName(_fromUtf8("groupBox_mix"))
        self.radioButton_on = QtGui.QRadioButton(self.groupBox_mix)
        self.radioButton_on.setGeometry(QtCore.QRect(0, 30, 51, 22))
        self.radioButton_on.setChecked(False)
        self.radioButton_on.setObjectName(_fromUtf8("radioButton_on"))
        self.radioButton_off = QtGui.QRadioButton(self.groupBox_mix)
        self.radioButton_off.setGeometry(QtCore.QRect(60, 30, 51, 22))
        self.radioButton_off.setChecked(True)
        self.radioButton_off.setObjectName(_fromUtf8("radioButton_off"))
        self.label_alt1 = QtGui.QLabel(Form)
        self.label_alt1.setGeometry(QtCore.QRect(320, 20, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt1.setFont(font)
        self.label_alt1.setObjectName(_fromUtf8("label_alt1"))
        self.label_alt2 = QtGui.QLabel(Form)
        self.label_alt2.setGeometry(QtCore.QRect(320, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_alt2.setFont(font)
        self.label_alt2.setObjectName(_fromUtf8("label_alt2"))
        self.lineEdit_alt1 = QtGui.QLineEdit(Form)
        self.lineEdit_alt1.setGeometry(QtCore.QRect(390, 20, 311, 27))
        self.lineEdit_alt1.setObjectName(_fromUtf8("lineEdit_alt1"))
        self.lineEdit_alt2 = QtGui.QLineEdit(Form)
        self.lineEdit_alt2.setGeometry(QtCore.QRect(390, 70, 311, 27))
        self.lineEdit_alt2.setObjectName(_fromUtf8("lineEdit_alt2"))
        self.label.raise_()
        self.progressBar_v1.raise_()
        self.progressBar_v2.raise_()
        self.progressBar_v3.raise_()
        self.pushButton_v1_enviar.raise_()
        self.spinBox_v1.raise_()
        self.pushButton_v2_enviar.raise_()
        self.spinBox_v2.raise_()
        self.pushButton_v3_enviar.raise_()
        self.spinBox_v3.raise_()
        self.lineEdit_t1.raise_()
        self.lineEdit_t2.raise_()
        self.lineEdit_mix.raise_()
        self.progressBar_t1.raise_()
        self.progressBar_t2.raise_()
        self.groupBox_mix.raise_()
        self.label_alt1.raise_()
        self.label_alt2.raise_()
        self.lineEdit_alt1.raise_()
        self.lineEdit_alt2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Supervisório", None))
        self.pushButton_v1_enviar.setText(_translate("Form", "Enviar", None))
        self.pushButton_v2_enviar.setText(_translate("Form", "Enviar", None))
        self.pushButton_v3_enviar.setText(_translate("Form", "Enviar", None))
        self.lineEdit_t1.setInputMask(_translate("Form", "0000.0 litros; ", None))
        self.lineEdit_t1.setText(_translate("Form", "0.0 litros", None))
        self.lineEdit_t2.setInputMask(_translate("Form", "000.0 litros; ", None))
        self.lineEdit_t2.setText(_translate("Form", "0.0 litros", None))
        self.groupBox_mix.setTitle(_translate("Form", "Misturador", None))
        self.radioButton_on.setText(_translate("Form", "On", None))
        self.radioButton_off.setText(_translate("Form", "Off", None))
        self.label_alt1.setText(_translate("Form", "Tanque 1:", None))
        self.label_alt2.setText(_translate("Form", "Tanque 2:", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

